using System;
using System.IO;
using System.Text;

class Restore
{
    static void Main()
    {
        string target = @"C:\проверка связи\Work_Practice\WorkPracticeLauncher\Program.cs";
        var enc = new UTF8Encoding(false);
        
        using (var sw = new StreamWriter(target, false, enc))
        {
            sw.NewLine = "\r\n";
            
            void W(string s) { sw.WriteLine(s); }
            
            W("using System;");
            W("using System.Diagnostics;");
            W("using System.IO;");
            W("using System.Net.Http;");
            W("using System.IO.Compression;");
            W("using System.Text;");
            W("using System.Threading;");
            W("using WorkPracticeLauncher.Tasks;");
            W("");
            W("namespace WorkPracticeLauncher");
            W("{");
            W("\tclass Program");
            W("\t{");
            W("\t\tprivate static int inputRow;");
            W("\t\tprivate static int inputCol;");
            W("\t\tprivate static string inputBuffer = \"\";");
            W("\t\tprivate static bool cancelAnimation = false;");
            W("");
            W("\t\tprivate static bool showCursorState = true;");
            W("\t\tprivate static DateTime lastCursorToggle = DateTime.Now;");
            W("\t\tprivate static readonly int cursorBlinkInterval = 500;");
            W("");
            W("\t\tprivate static int lastWidth;");
            W("\t\tprivate static int lastHeight;");
            W("\t\tprivate static bool isWindowsTerminal;");
            W("\t\tprivate static bool supportsEmoji;");
            W("");
            W("\t\tpublic static bool IsWindowsTerminal { get; private set; }");
            W("\t\tpublic static bool SupportsEmoji => supportsEmoji;");
            W("");
            W("\t\tstatic void Main()");
            W("\t\t{");
            W("\t\t\tConsole.OutputEncoding = Encoding.UTF8;");
            W("\t\t\tConsole.Clear();");
            W("");
            W("\t\t\tisWindowsTerminal = !string.IsNullOrEmpty(Environment.GetEnvironmentVariable(\"WT_SESSION\"));");
            W("\t\t\tIsWindowsTerminal = isWindowsTerminal;");
            W("");
            W("\t\t\tsupportsEmoji = TestEmojiSupport();");
            W("");
            W("\t\t\tlastWidth = Console.WindowWidth;");
            W("\t\t\tlastHeight = Console.WindowHeight;");
            W("");
            W("\t\t\tShowTerminalRecommendation();");
            W("");
            W("\t\t\tCatAnimation cat = new CatAnimation();");
            W("");
            W("\t\t\tRedrawScreen(cat);");
            W("\t\t\tResetCursorState();");
            W("");
            W("\t\t\tif (isWindowsTerminal)");
            W("\t\t\t{");
            W("\t\t\t\tThread.Sleep(150);");
            W("\t\t\t\tlastWidth = Console.WindowWidth;");
            W("\t\t\t\tlastHeight = Console.WindowHeight;");
            W("\t\t\t\tRedrawScreen(cat);");
            W("\t\t\t\tResetCursorState();");
            W("\t\t\t}");
            W("");
            W("\t\t\tbool running = true;");
            W("");
            W("\t\t\twhile (running)");
            W("\t\t\t{");
            W("\t\t\t\tif (Console.WindowWidth != lastWidth || Console.WindowHeight != lastHeight)");
            W("\t\t\t\t{");
            W("\t\t\t\t\tlastWidth = Console.WindowWidth;");
            W("\t\t\t\t\tlastHeight = Console.WindowHeight;");
            W("\t\t\t\t\tRedrawScreen(cat);");
            W("\t\t\t\t\tResetCursorState();");
            W("\t\t\t\t\tif (supportsEmoji)");
            W("\t\t\t\t\t{");
            W("\t\t\t\t\t\tThread.Sleep(30);");
            W("\t\t\t\t\t\tRedrawScreen(cat);");
            W("\t\t\t\t\t\tResetCursorState();");
            W("\t\t\t\t\t}");
            W("\t\t\t\t}");
            W("");
            W("\t\t\t\tcat.UpdateSleep();");
            W("\t\t\t\tDrawCursor();");
            W("");
            W("\t\t\t\tif (Console.KeyAvailable)");
            W("\t\t\t\t{");
            W("\t\t\t\t\tConsoleKeyInfo keyInfo = Console.ReadKey(true);");
            W("\t\t\t\t\tConsoleKey key = keyInfo.Key;");
            W("\t\t\t\t\tchar keyChar = keyInfo.KeyChar;");
            W("");
            W("\t\t\t\t\tbool isValidKey = (key >= ConsoleKey.D0 && key <= ConsoleKey.D4) ||");
            W("\t\t\t\t\t\t\t\t\t  (key == ConsoleKey.Enter) ||");
            W("\t\t\t\t\t\t\t\t\t  (key == ConsoleKey.Backspace) ||");
            W("\t\t\t\t\t\t\t\t\t  (key == ConsoleKey.Escape);");
            W("");
            W("\t\t\t\t\tif (!isValidKey) continue;");
            W("");
            W("\t\t\t\t\tif (key >= ConsoleKey.D0 && key <= ConsoleKey.D4)");
            W("\t\t\t\t\t{");
            W("\t\t\t\t\t\tif (inputBuffer.Length > 0)");
            W("\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\tConsole.SetCursorPosition(inputCol, inputRow);");
            W("\t\t\t\t\t\t\tConsole.Write(new string(' ', inputBuffer.Length + 1));");
            W("\t\t\t\t\t\t\tinputBuffer = \"\";");
            W("\t\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\t}");
            W("");
            W("\t\t\t\t\t\tinputBuffer = keyChar.ToString();");
            W("\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\tDrawCursor();");
            W("");
            W("\t\t\t\t\t\tcancelAnimation = false;");
            W("\t\t\t\t\t\tThread animThread = new Thread(() =>");
            W("\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\tcat.WakeUpWithCancel(() => cancelAnimation);");
            W("\t\t\t\t\t\t});");
            W("\t\t\t\t\t\tanimThread.Start();");
            W("");
            W("\t\t\t\t\t\tbool cancelled = false;");
            W("\t\t\t\t\t\twhile (animThread.IsAlive)");
            W("\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\tif (Console.KeyAvailable)");
            W("\t\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\t\tConsoleKey checkKey = Console.ReadKey(true).Key;");
            W("\t\t\t\t\t\t\t\tif (checkKey == ConsoleKey.Enter)");
            W("\t\t\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\t\t\tcancelAnimation = true;");
            W("\t\t\t\t\t\t\t\t\tbreak;");
            W("\t\t\t\t\t\t\t\t}");
            W("\t\t\t\t\t\t\t\telse if (checkKey == ConsoleKey.Backspace || checkKey == ConsoleKey.Escape)");
            W("\t\t\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\t\t\tcancelAnimation = true;");
            W("\t\t\t\t\t\t\t\t\tcancelled = true;");
            W("\t\t\t\t\t\t\t\t\tbreak;");
            W("\t\t\t\t\t\t\t\t}");
            W("\t\t\t\t\t\t\t}");
            W("\t\t\t\t\t\t\tThread.Sleep(10);");
            W("\t\t\t\t\t\t}");
            W("\t\t\t\t\t\tanimThread.Join(100);");
            W("");
            W("\t\t\t\t\t\twhile (Console.KeyAvailable) Console.ReadKey(true);");
            W("");
            W("\t\t\t\t\t\tif (cancelled)");
            W("\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\tConsole.SetCursorPosition(inputCol, inputRow);");
            W("\t\t\t\t\t\t\tConsole.Write(new string(' ', inputBuffer.Length + 1));");
            W("\t\t\t\t\t\t\tinputBuffer = \"\";");
            W("\t\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\t\tRedrawScreen(cat);");
            W("\t\t\t\t\t\t\tResetCursorState();");
            W("\t\t\t\t\t\t\tcontinue;");
            W("\t\t\t\t\t\t}");
            W("");
            W("\t\t\t\t\t\tif (cancelAnimation)");
            W("\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\tint choice = int.Parse(inputBuffer);");
            W("\t\t\t\t\t\t\tinputBuffer = \"\";");
            W("\t\t\t\t\t\t\tConsole.SetCursorPosition(inputCol, inputRow);");
            W("\t\t\t\t\t\t\tConsole.Write(new string(' ', 2));");
            W("\t\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\t\tConsole.Clear();");
            W("\t\t\t\t\t\t\tExecuteChoice(choice);");
            W("\t\t\t\t\t\t\tif (choice == 0)");
            W("\t\t\t\t\t\t\t\trunning = false;");
            W("\t\t\t\t\t\t\telse");
            W("\t\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\t\tRedrawScreen(cat);");
            W("\t\t\t\t\t\t\t\tResetCursorState();");
            W("\t\t\t\t\t\t\t}");
            W("\t\t\t\t\t\t\tcontinue;");
            W("\t\t\t\t\t\t}");
            W("\t\t\t\t\t\telse");
            W("\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\tstring digit = inputBuffer;");
            W("\t\t\t\t\t\t\tinputBuffer = \"\";");
            W("\t\t\t\t\t\t\tRedrawScreen(cat);");
            W("\t\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\t\tif (!string.IsNullOrEmpty(digit))");
            W("\t\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\t\tinputBuffer = digit;");
            W("\t\t\t\t\t\t\t\tDrawCursor();");
            W("\t\t\t\t\t\t\t}");
            W("\t\t\t\t\t\t\tResetCursorState();");
            W("\t\t\t\t\t\t}");
            W("\t\t\t\t\t}");
            W("\t\t\t\t\telse if (key == ConsoleKey.Enter && !string.IsNullOrEmpty(inputBuffer))");
            W("\t\t\t\t\t{");
            W("\t\t\t\t\t\tint choice = int.Parse(inputBuffer);");
            W("\t\t\t\t\t\tinputBuffer = \"\";");
            W("\t\t\t\t\t\tConsole.SetCursorPosition(inputCol, inputRow);");
            W("\t\t\t\t\t\tConsole.Write(new string(' ', 2));");
            W("\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\twhile (Console.KeyAvailable) Console.ReadKey(true);");
            W("\t\t\t\t\t\tConsole.Clear();");
            W("\t\t\t\t\t\tExecuteChoice(choice);");
            W("\t\t\t\t\t\tif (choice == 0)");
            W("\t\t\t\t\t\t\trunning = false;");
            W("\t\t\t\t\t\telse");
            W("\t\t\t\t\t\t{");
            W("\t\t\t\t\t\t\tRedrawScreen(cat);");
            W("\t\t\t\t\t\t\tResetCursorState();");
            W("\t\t\t\t\t\t}");
            W("\t\t\t\t\t}");
            W("\t\t\t\t\telse if (key == ConsoleKey.Backspace && !string.IsNullOrEmpty(inputBuffer))");
            W("\t\t\t\t\t{");
            W("\t\t\t\t\t\tinputBuffer = \"\";");
            W("\t\t\t\t\t\tConsole.SetCursorPosition(inputCol, inputRow);");
            W("\t\t\t\t\t\tConsole.Write(new string(' ', 2));");
            W("\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\twhile (Console.KeyAvailable) Console.ReadKey(true);");
            W("\t\t\t\t\t}");
            W("\t\t\t\t\telse if (key == ConsoleKey.Escape)");
            W("\t\t\t\t\t{");
            W("\t\t\t\t\t\tinputBuffer = \"\";");
            W("\t\t\t\t\t\tConsole.SetCursorPosition(inputCol, inputRow);");
            W("\t\t\t\t\t\tConsole.Write(new string(' ', 2));");
            W("\t\t\t\t\t\tSetCursorToInput();");
            W("\t\t\t\t\t\twhile (Console.KeyAvailable) Console.ReadKey(true);");
            W("\t\t\t\t\t\trunning = false;");
            W("\t\t\t\t\t}");
            W("\t\t\t\t}");
            W("");
            W("\t\t\t\tThread.Sleep(30);");
            W("\t\t\t}");
            W("");
            W("\t\t\tConsole.Clear();");
            W("\t\t\tConsole.CursorVisible = true;");
            W("\t\t}");
            W("");
        }
        Console.WriteLine("Part 1 written OK");
    }
}